#!/usr/bin/env python3
"""Build the airline logo sheets Select Sky draws from; run it after AIRLINES changes in skydata.py.

Logos come from github.com/Jxck-S/airline-logos (FlightAware's square logos, named by ICAO
code, with RadarBox's as the fallback), pinned to one commit so a rebuild gives the same art.
Each sheet holds 16 logos in a 4 x 4 grid at two sizes: 48 px for the WALL tile and the track
header, 16 px for table rows. Sheets keep the app under the importer's 128 files, and the badge
loads only the ones it needs.

Writes select_sky/logos/*.png and select_sky/skylogodata.py. Needs Pillow; downloads are
cached in .cache/logos/ so a rebuild works offline.
"""

from pathlib import Path
import sys
import urllib.request

from PIL import Image

REPO = "Jxck-S/airline-logos"
COMMIT = "e0b218991caef4832e0db911136173e8eead942a"
SOURCES = ("flightaware_logos", "radarbox_logos")      # first hit wins
SIZES = (48, 16)
COLS = 4
PER_SHEET = 16
SKIP = {"FLE"}          # the source file is a plain black disc, not Flair's logo

# Logos that vanish on the dark panel (RAISED, 33 32 33) sit on a light plate instead: those where
# under LIGHT_SHARE of the visible pixels reach LIGHT_CONTRAST against it, unless the logo brings its
# own full-bleed background (opaque over FULL_BLEED of its square).
PANEL = (33, 32, 33)
LIGHT_CONTRAST, LIGHT_SHARE, FULL_BLEED = 2.0, 0.42, 0.6

ROOT = Path(__file__).resolve().parents[1]
CACHE = ROOT / ".cache" / "logos"
OUT = ROOT / "select_sky" / "logos"
DATA = ROOT / "select_sky" / "skylogodata.py"


def airlines():
    sys.path.insert(0, str(ROOT / "select_sky"))
    import skydata
    return sorted(skydata.AIRLINES)


def fetch(code):
    """The cached source PNG for an ICAO code, downloading it on first use; None when no source has one."""
    for folder in SOURCES:
        path = CACHE / folder / (code + ".png")
        if path.exists():
            return path
        url = "https://raw.githubusercontent.com/%s/%s/%s/%s.png" % (REPO, COMMIT, folder, code)
        try:
            data = urllib.request.urlopen(url, timeout=20).read()
        except urllib.error.HTTPError as e:
            if e.code == 404:
                continue
            raise
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(data)
        return path
    return None


def _lum(r, g, b):
    def lin(c):
        c /= 255
        return c / 12.92 if c <= 0.03928 else ((c + 0.055) / 1.055) ** 2.4
    return 0.2126 * lin(r) + 0.7152 * lin(g) + 0.0722 * lin(b)


def needs_plate(img):
    px = [p for p in img.getdata() if p[3] > 128]
    if not px or len(px) > FULL_BLEED * img.width * img.height:
        return False
    bg = _lum(*PANEL) + 0.05
    seen = sum(1 for p in px if (_lum(*p[:3]) + 0.05) / bg >= LIGHT_CONTRAST)
    return seen < LIGHT_SHARE * len(px)


def main():
    codes, art = [], []
    for code in airlines():
        if code in SKIP:
            continue
        path = fetch(code)
        if path is None:
            print("no logo for", code)
            continue
        codes.append(code)
        art.append(Image.open(path).convert("RGBA"))

    OUT.mkdir(exist_ok=True)
    for old in OUT.glob("*.png"):
        old.unlink()
    sheets = (len(codes) + PER_SHEET - 1) // PER_SHEET
    for size in SIZES:
        for s in range(sheets):
            sheet = Image.new("RGBA", (COLS * size, (PER_SHEET // COLS) * size), (0, 0, 0, 0))
            for cell, img in enumerate(art[s * PER_SHEET:(s + 1) * PER_SHEET]):
                sheet.paste(img.resize((size, size), Image.LANCZOS), ((cell % COLS) * size, (cell // COLS) * size))
            # A palettised PNG stays one byte a pixel on the badge: a quarter of the RAM and file size,
            # and 256 colours per 16 logos shows no loss.
            sheet = sheet.quantize(256, method=Image.FASTOCTREE, dither=Image.NONE)
            sheet.save(OUT / ("%d_%d.png" % (size, s)), optimize=True)

    light = [c for c, img in zip(codes, art) if needs_plate(img.resize((48, 48), Image.LANCZOS))]
    DATA.write_text(
        '"""Airline logo index. Generated by scripts/build_logos.py from %s@%s; do not edit."""\n\n'
        "# Logo n is cell n %% %d of logos/<size>_<n // %d>.png, a %d-column grid.\n"
        "CODES = %r\n"
        "SIZES = %r\n"
        "PER_SHEET, COLS = %d, %d\n"
        "# Dark logos drawn on a light plate.\n"
        "LIGHT = %r\n" % (REPO, COMMIT[:7], PER_SHEET, PER_SHEET, COLS, "".join(codes), SIZES, PER_SHEET, COLS, "".join(light)))
    total = sum(p.stat().st_size for p in OUT.glob("*.png"))
    print("%d logos, %d sheets a size, %d on a light plate, %d bytes of PNG" % (len(codes), sheets, len(light), total))


if __name__ == "__main__":
    main()
